#!/bin/bash
# Shebang is for Terraform script provisioner

REPO_URL=https://github.com/rchain/rchain-ethereum-node
REPO_DIR=/opt/rchain-ethereum-node
GIT_CRYPT_KEY_FILE=/root/rchain-sre-git-crypt-key
SETUP_SCRIPT_URL=https://raw.githubusercontent.com/rchain/rchain-ethereum-node/master/update-run-setup
REPO_BRANCH=dev

if [[ -z "$SETUP_SCRIPT_RUNNING" ]]; then
	ln -sf $REPO_DIR/bootstrap${PROFILE:+.$PROFILE} $REPO_DIR.profile
	source <(curl -fsSL "$SETUP_SCRIPT_URL")
fi
