#!/bin/bash
set -e -o pipefail

PARITY_VERS='2.5.0'

while :; do
	_hostname="$(hostname -f)"
	if [[ $_hostname == *.* && $_hostname != *.internal ]]; then
		break
	fi
	systemctl restart systemd-networkd
	echo "Waiting for FQDN..."
	sleep 10
done

apt install -y --no-install-recommends \
    apt-transport-https gnupg2 software-properties-common \
    collectd liboping0 \
	bpfcc-tools iotop \
	coreutils psmisc less vim rsync screen tree jq dnsutils

install -C -m644 collectd.conf -t /etc/collectd/
systemctl restart collectd

if ! getent passwd ether >/dev/null; then
	useradd -rM -s /bin/false -d /home/ether ether
	install -m700 -d /home/ether
fi

if ! blkid /dev/disk/by-id/google-ethereum-node-data >/dev/null; then
	mkfs.ext4 -q /dev/disk/by-id/google-ethereum-node-data
fi

systemctl link $PWD/home-ether.mount
systemctl daemon-reload
systemctl enable --now home-ether.mount

chmod 700 /home/ether
chown ether. /home/ether

curl -fsSL -z /usr/local/bin/parity -o /usr/local/bin/parity \
	"https://releases.parity.io/ethereum/v$PARITY_VERS/x86_64-unknown-linux-gnu/parity"
chmod +x /usr/local/bin/parity

install -C -m755 start-parity -t /usr/local/bin/

systemctl link $PWD/parity.service
systemctl daemon-reload
systemctl enable --now parity
